default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wedding_development

test:
  <<: *default
  database: wedding_test

production:
  host: localhost
  port: 5432
  database: wedding_production
  username: wedding
  password: <%= ENV['WEDDING_DATABASE_PASSWORD'] %>
